name: Prisma Migrate

on:
  push:
    branches:
      - main

jobs:
  prisma_migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run yarn install
        run: yarn install

      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cd packages/prisma && npx prisma migrate

